### PR TITLE
Use the existing redhat-operators catalog as catalog source

### PR DESCRIPTION
**Pull request by rrati**

### CODE REVIEW

**Comment by apahim** [comment]
I was under the impression that we were going to just apply a Subscription to the cluster... did we change that thinking?

**Comment by rrati** [comment]
The upstream-community-operators aren't in the curated list of operators afaik.  What catalog would the subscription subscribe to?

**Comment by apahim** [comment]
We don't use the curated operators... that was discontinued. I see the Quay Security Operator in the OperatorHub of a newly created OSD cluster.

**Comment by apahim** [comment]
Screenshot from 2020-10-29 15-41-56

**Comment by rrati** [comment]
Is that a cluster that has gone through the cluster onboarding docs?  When I looked it a cluster it wasn't clear what the catalog source was for that operator.

**Comment by apahim** [comment]
No, that's a brand new cluster, created today on stage.

**Comment by apahim** [comment]
https://console-openshift-console.apps.apahim-test-mt.c5q0.s1.devshift.org/

**Comment by rrati** [comment]
Ah, excellent.  We should just be able to update the subscription and remove the catalog source then.

**Comment by rrati** [comment]
I can't think of a good pr_check for this since it's just a few openshift objects at this point.  If you can't think of anything either then I'll remove the pr_check script as well (and corresponding jenkins config)

**Comment by rrati** [comment]
Found a pr_check that makes sense for this.

**Comment by rrati** [comment]
@apahim Look good?

**Comment by rrati** [comment]
After testing, this works fine for a new install.  It will not work for an existing operator installation though.  Updating the subscription isn't enough to trigger OLM to install the operator.

**Pull request merged**
